#!/bin/bash

# modulo: demonstrate the modulo operator

for (( i = 0; i <= 20; ++i )); do
	remainder=$((i % 5))
	if (( (i % 5) == 0 )); then
		printf "<%d> " ${i}
	else
		printf "%d " ${i}
	fi
done
printf "\n"
exit
