(define (sum-squares-two-max x y z)
  (cond ((> x y) (if (> y z)
				     (+ (* x x) (* y y))
					 (+ (* x x) (* z z))))
		((> x z) (if (> z y)
				     (+ (* x x) (* z z))
					 (+ (* x x) (* y y))))
		(else (+ (* y y) (* z z)))))

(sum-squares-two-max 1 2 3)
(sum-squares-two-max 1 3 2)
(sum-squares-two-max 2 1 3)
(sum-squares-two-max 2 3 1)
(sum-squares-two-max 3 2 1)
(sum-squares-two-max 3 1 2)
; seems to work!
